### ISSUE TITLE
Making the code style a little more idiomatic

### ISSUE THREAD

**Issue by djc** [vivint-smarthome/opentelemetry-stackdriver#11]
Currently the rustfmt.toml option selection is pretty far from the default, which I personally find a little jarring and harder to work with. Would you be open to just reverting to rustfmt's defaults, or, if not, just reverting the indentation to default?

**Comment by Xaeroxe** [comment]
That formatting is standard at Vivint, and the two space indent is the most important aspect of it. Sorry, this is going to stay.

**Comment by djc** [comment]
Fair enough.
